app = '2mrrw-hls-transcoder'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  LOG_LEVEL    = "info"
  IDLE_POLL_MS = "5000"

[[vm]]
  memory   = '2gb'
  cpu_kind = 'shared'
  cpus     = 2
